services:
  sharelatex:
    image: dangdoan2003/sharelatex:latest
    environment:
      OVERLEAF_MONGO_URL: 'mongo db url'
      # 💀 Set this        ^^^^^^^^^^^^
      OVERLEAF_REDIS_HOST: 'redis server host'
      # 💀 Set this         ^^^^^^^^^^^^^^^^^
      OVERLEAF_REDIS_PORT: 'redis server port'
      # 💀 Set this         ^^^^^^^^^^^^^^^^^
      OVERLEAF_APP_NAME: "D-Dev's Overleaf"
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      OVERLEAF_BEHIND_PROXY: 'true'
      OVERLEAF_SECURE_COOKIE: 'true'
      OVERLEAF_SITE_URL: 'https://overleaf.dangdd.me'
      OVERLEAF_ADMIN_EMAIL: 'sorry@not.for.public.use'
      OVERLEAF_LEFT_FOOTER: '[{"text": "From D-Dev with love", "url": "https://dangdd.me"}]'
      OVERLEAF_RIGHT_FOOTER: '[{"text": "Hosted by D-Dev"}]'
    stop_grace_period: 60s
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/srv/overleaf:/var/lib/overleaf'
      #  ^^^^^^^^^^^^^ Set on the node that run this service💀
      - '/srv/overleaf/log:/var/log/overleaf'
      #  ^^^^^^^^^^^^^^^^^ Set on the node that run this service💀
    deploy:
      placement:
        constraints:
          - 'node.hostname==d2'
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        mode: host
        protocol: tcp
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/root/overleaf/nginx.conf:/etc/nginx/nginx.conf:ro'
      #  ^^^^^^^^^^^^^^^^^^^^^^^^^ Set on the node that run this service💀
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      #  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Set on the node that run this service💀
    deploy:
      placement:
        constraints:
          - 'node.hostname==d2'
    depends_on:
      - sharelatex

  redis:
    image: redis:latest
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/home/admin/redis-data:/data'
      #  ^^^^^^^^^^^^^^^^^^^^^^ Set on the node that run this service💀
    ports:
      - target: 6379
        published: 6379
        mode: host
        protocol: tcp
    deploy:
      placement:
        constraints:
          - 'node.hostname==d3'
