name: Docker Image Builder

on: workflow_dispatch

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.actor }}/sharelatex
  # Tex live year version
  TEXLIVE_YEAR: 2024

jobs:
  build-image-and-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          repository: "overleaf/toolkit"

      - name: Start sharelatex images
        run: |
          ./bin/init
          ./bin/up -d

      - name: Setup sharelatex images as production ready overleaf server
        run: |
          docker exec sharelatex apt update
          docker exec sharelatex apt upgrade -y
          docker exec sharelatex apt install inkscape python3-pygments -y
          docker exec sharelatex bash -c echo "shell_escape = t" >> /usr/local/texlive/${{ env.TEXLIVE_YEAR }}/texmf.cnf
          docker exec sharelatex mkdir -p /usr/local/lib/latexmk
          docker exec sharelatex touch  /usr/local/lib/latexmk/latexmkrc
          docker exec sharelatex echo "# Fix generating of glossaries
          # Source: https://github.com/overleaf/docker-image/issues/6#issuecomment-282931678
          add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
          sub makeglo2gls {
              system("makeindex -s '$_[0]'.ist -t '$_[0]'.glg -o '$_[0]'.gls '$_[0]'.glo");
          }

          add_cus_dep('acn', 'acr', 0, 'makeacn2acr');
          sub makeacn2acr {
              system("makeindex -s \"$_[0].ist\" -t \"$_[0].alg\" -o \"$_[0].acr\" \"$_[0].acn\"");
          }" >> "/usr/local/lib/latexmk/latexmkrc"
          docker exec sharelatex tlmgr install scheme-full

      - name: Recheck created files
        run: |
          docker exec sharelatex cat /usr/local/texlive/${{ env.TEXLIVE_YEAR }}/texmf.cnf
          docker exec sharelatex cat /usr/local/lib/latexmk/lcatexmkrc

      - name: Commit new version
        run: docker commit sharelatex ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-full-setup

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry ${{ env.REGISTRY }}
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-full-setup
