name: Docker Image Builder

on: workflow_dispatch

env:
  # Defined registries
  REGISTRY1: ghcr.io
  REGISTRY2: docker.io
  # Image name
  BASE_IMAGE_NAME: sharelatex-base
  FULL_IMAGE_NAME: sharelatex

jobs:
  build-image-and-push-full-version:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          repository: overleaf/overleaf

      - name: Get Dockerfile
        run: |
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.actor }}/overleaf-fullsetup.git
          cp overleaf-fullsetup/Dockerfile server-ce/Dockerfile
          rm -rf overleaf-fullsetup

      - name: Set build env
        id: build_env
        run: |
          echo "date=$(TZ=Asia/Ho_Chi_Minh date +"%m-%d-%Y")" >> "$GITHUB_OUTPUT"
          echo "MONOREPO_REVISION=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Check build env
        run: |
          echo "Current build date: ${{ steps.build_env.outputs.date }}"
          echo "Current repo commit hash: ${{ steps.build_env.outputs.MONOREPO_REVISION }}"

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Docker login registry ${{ env.REGISTRY1 }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY1 }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker login registry ${{ env.REGISTRY2 }}
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server-ce/Dockerfile-base
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            TEXLIVE_MIRROR=${{ vars.TEXLIVE_MIRROR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.BASE_IMAGE_NAME }}:latest
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.BASE_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.BASE_IMAGE_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.BASE_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
          push: true

      - name: Build full
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server-ce/Dockerfile
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            MONOREPO_REVISION=${{ steps.build_env.outputs.MONOREPO_REVISION }}
            OVERLEAF_BASE_TAG=${{ vars.DOCKER_USERNAME }}/${{ env.BASE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.FULL_IMAGE_NAME }}:latest
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.FULL_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.FULL_IMAGE_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.FULL_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
          push: true
