name: Docker Image Builder

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  # Defined registries
  REGISTRY1: ghcr.io
  REGISTRY2: docker.io
  # Image name
  BASE_IMAGE_NAME: sharelatex-base
  FULL_IMAGE_NAME: sharelatex

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          repository: overleaf/overleaf

      - name: Edit Dockerfile
        run: |
          sed -i \
            -e 's|^ARG OVERLEAF_BASE_TAG=.*|ARG OVERLEAF_BASE_TAG=dangdoan2003/sharelatex-base:latest|' \
            -e '/^FROM \$OVERLEAF_BASE_TAG$/a\
          ARG TEXLIVE_MIRROR=https://mirrors.mit.edu/CTAN/systems/texlive/tlnet\
          \
          # Fully set up image as production ready\
          RUN apt-get update \&\& apt-get upgrade -y \&\& \\\
            DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\
              git fontconfig pandoc python3 python3-pygments imagemagick ghostscript \\\
              librsvg2-bin make chktex lacheck fonts-liberation fonts-linuxlibertine \&\& \\\
            sed -i "s/<policy domain=\\"coder\\" rights=\\"none\\" pattern=\\"PDF\\" \/>/<policy domain=\\"coder\\" rights=\\"read|write\\" pattern=\\"PDF\\" \/>/" /etc/ImageMagick-6/policy.xml 2>/dev/null || true \&\& \\\
            echo "shell_escape = t" >> $(find /usr/local/texlive/ -type d -name "20*")/texmf.cnf \&\& \\\
            tlmgr option repository "$TEXLIVE_MIRROR" \&\& \\\
            tlmgr install --persistent-downloads scheme-full \&\& \\\
            tlmgr path add \&\& \\\
            fc-cache -f -v \&\& \\\
            apt-get clean \&\& rm -rf /var/lib/apt/lists/*' \
            server-ce/Dockerfile

      - name: Set build env
        id: build_env
        run: |
          echo "date=$(TZ=Asia/Ho_Chi_Minh date +"%Y-%m-%d")" >> "$GITHUB_OUTPUT"
          echo "MONOREPO_REVISION=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Check build env
        run: |
          echo "Current build date: ${{ steps.build_env.outputs.date }}"
          echo "Current repo commit hash: ${{ steps.build_env.outputs.MONOREPO_REVISION }}"

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Docker login registry ${{ env.REGISTRY1 }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY1 }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker login registry ${{ env.REGISTRY2 }}
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server-ce/Dockerfile-base
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            TEXLIVE_MIRROR=${{ vars.TEXLIVE_MIRROR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.BASE_IMAGE_NAME }}:latest
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.BASE_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.BASE_IMAGE_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.BASE_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
          push: true

      - name: Build full
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server-ce/Dockerfile
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            MONOREPO_REVISION=${{ steps.build_env.outputs.MONOREPO_REVISION }}
            TEXLIVE_MIRROR=${{ vars.TEXLIVE_MIRROR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.FULL_IMAGE_NAME }}:latest
            ${{ env.REGISTRY1 }}/${{ github.actor }}/${{ env.FULL_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.FULL_IMAGE_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.FULL_IMAGE_NAME }}:${{ steps.build_env.outputs.date }}
          push: true
